import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Authprovider } from "@/context/Authprovider";
import { ToastContainer } from "react-toastify";
import NavbarWrapper from "@/Components/NavbarWrapper";
import FooterWrapper from "@/Components/FooterWrapper";
import { Toaster } from "react-hot-toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Career Flow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Authprovider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
        >
          <NavbarWrapper />
          {children}
          <ToastContainer position="top-right" autoClose={3000} />
          <Toaster position="top-right" />
          <FooterWrapper />
        </body>
      </Authprovider>
    </html>
  );
}
